export const vertexShader=`#version 300 es
precision highp float;layout(location=0) in vec2 a_position;uniform vec2 u_resolution;uniform float u_imageAspectRatio,u_scale,u_rotation,u_offsetX,u_offsetY;out vec2 v_imageUV;out vec2 v_patternUV;
void main(){gl_Position=vec4(a_position,0.,1.);vec2 p=a_position*.5;p.x*=u_resolution.x/u_resolution.y;float r=radians(u_rotation);p=mat2(cos(r),-sin(r),sin(r),cos(r))*((p-vec2(u_offsetX,-u_offsetY)*.15)/u_scale);p.x/=u_imageAspectRatio;v_imageUV=p+.5;v_patternUV=p*4.;}`;
export const fragmentShader=`#version 300 es
precision highp float;uniform sampler2D u_image;uniform float u_time,u_imageAspectRatio,u_speed,u_contour,u_softness,u_repetition,u_distortion,u_shiftRed,u_shiftBlue,u_angle,u_innerDistortion,u_outerDistortion,u_innerGlow,u_outerGlow,u_smokeOffset,u_size;uniform int u_effect;in vec2 v_imageUV;in vec2 v_patternUV;out vec4 outColor;
float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+1.),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=n(p)*a;p=p*2.+2.2;a*=.5;}return v;}vec3 palette(float x){return mix(vec3(.02,.32,.08),vec3(.8,1.,.1),smoothstep(.25,.82,x));}
void main(){float time=u_time*u_speed;vec2 flow=vec2(fbm(v_patternUV*u_repetition+time*.12),fbm(v_patternUV*u_repetition-time*.1))-.5;vec2 liquidUV=v_imageUV+flow*u_distortion*.085;float alpha=texture(u_image,liquidUV).a;float aa=fwidth(alpha)*1.5;float mask=smoothstep(u_contour-u_softness-aa,u_contour+u_softness+aa,alpha);float edge=mask-smoothstep(.18,.72,alpha);vec3 color=vec3(0.);
if(u_effect==1){float bands=sin((v_patternUV.x*cos(u_angle)+v_patternUV.y*sin(u_angle))*u_repetition*5.+flow.x*8.+time)*.5+.5;vec2 redUV=liquidUV+normalize(flow+.001)*u_shiftRed*.006;vec2 blueUV=liquidUV-normalize(flow+.001)*u_shiftBlue*.006;float chroma=texture(u_image,redUV).a-texture(u_image,blueUV).a;vec3 metal=mix(vec3(.004,.007,.006),vec3(.93,.98,.88),smoothstep(.2,.9,bands));color=metal*mask;color+=vec3(.7,1.,.5)*edge*(1.5+u_innerGlow);color+=vec3(.2,.8,.4)*chroma*.6;}
else if(u_effect==0){float heat=fbm(v_patternUV*1.7+time*.12);vec3 low=vec3(.05,.12,.65),mid=vec3(.2,.7,1.),hot=vec3(1.,.25,.01);color=mix(low,mid,smoothstep(.1,.65,heat));color=mix(color,hot,smoothstep(.68,1.,heat));color*=mask;color+=vec3(.8,.95,1.)*edge*(1.+u_innerGlow);}
else {float outerAlpha=texture(u_image,v_imageUV+flow*u_outerDistortion*.14).a;float innerAlpha=texture(u_image,v_imageUV-flow*u_innerDistortion*.06).a;float smoke=smoothstep(.02,.72,outerAlpha)*(0.25+.75*fbm(v_patternUV*u_size-time*.11));float inner=smoothstep(.1,.8,innerAlpha);color=vec3(.001,.018,.006)*mask;color+=palette(fbm(v_patternUV*2.+time*.1))*inner*mask*.72;color+=vec3(.65,1.,.14)*edge*(1.5+u_innerGlow);color+=vec3(0.,.72,.16)*smoke*(1.-mask*.45)*u_outerGlow;}
outColor=vec4(color,1.);}`;
