import { ShaderProgram } from './ShaderProgram';
import { TextureManager } from './TextureManager';
import { vertexShader, fragmentShader } from '../shaders/program';
export class PaperShaderRenderer {
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{alpha:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error('该浏览器不支持 WebGL2');this.program=new ShaderProgram(this.gl,vertexShader,fragmentShader);this.textures=new TextureManager(this.gl);this.values={};this.start=performance.now();this.setup();this.resize=this.resize.bind(this);window.addEventListener('resize',this.resize);this.resize();this.frame();}
  setup(){const {gl}=this;const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);this.program.use();const a=gl.getAttribLocation(this.program.program,'a_position');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);this.u=Object.fromEntries(['u_time','u_resolution','u_image','u_imageAspectRatio','u_effect','u_speed','u_scale','u_rotation','u_offsetX','u_offsetY','u_contour','u_softness','u_repetition','u_distortion','u_shiftRed','u_shiftBlue','u_angle','u_innerDistortion','u_outerDistortion','u_innerGlow','u_outerGlow','u_smokeOffset','u_size'].map(k=>[k,this.program.uniform(k)]));}
  resize(){const r=this.canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(r.width*ratio));this.canvas.height=Math.max(1,Math.round(r.height*ratio));this.gl.viewport(0,0,this.canvas.width,this.canvas.height);}
  setValues(v){this.values=v;} loadImage(file){const image=new Image();image.onload=()=>{this.textures.upload(image);URL.revokeObjectURL(image.src);};image.src=URL.createObjectURL(file);}
  frame(){const {gl,u,values:v}=this;gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT);this.program.use();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.textures.texture);gl.uniform1i(u.u_image,0);gl.uniform1f(u.u_time,(performance.now()-this.start)/1000);gl.uniform2f(u.u_resolution,this.canvas.width,this.canvas.height);gl.uniform1f(u.u_imageAspectRatio,this.textures.aspect);gl.uniform1i(u.u_effect,v.effect==='liquidMetal'?1:v.effect==='gemSmoke'?2:0);for(const [name,fallback] of [['u_speed',1],['u_scale',.6],['u_rotation',0],['u_offsetX',0],['u_offsetY',0],['u_contour',.52],['u_softness',.16],['u_repetition',2.2],['u_distortion',.2],['u_shiftRed',.28],['u_shiftBlue',.24],['u_angle',24],['u_innerDistortion',.82],['u_outerDistortion',.68],['u_innerGlow',.64],['u_outerGlow',.55],['u_smokeOffset',.08],['u_size',.86]])gl.uniform1f(u[name],v[name.replace('u_','')]??fallback);this.raf=requestAnimationFrame(()=>this.frame());gl.drawArrays(gl.TRIANGLES,0,6);}
  dispose(){cancelAnimationFrame(this.raf);window.removeEventListener('resize',this.resize);this.textures.dispose();this.program.dispose();}
}
